// <auto-generated />
using CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(ProductContextDb))]
    [Migration("20250302065555_initDatabase")]
    partial class initDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Smartphone"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tablet"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Laptop"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Smartwatch"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Iphone 12",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Iphone 11",
                            Price = 900m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "Samsung Galaxy S21",
                            Price = 800m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Name = "Samsung Galaxy S20",
                            Price = 700m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Samsung Galaxy S10",
                            Price = 600m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Samsung Galaxy S9",
                            Price = 500m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Samsung Galaxy S8",
                            Price = 400m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Samsung Galaxy S7",
                            Price = 300m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Samsung Galaxy S6",
                            Price = 200m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Samsung Galaxy S5",
                            Price = 100m
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Product", b =>
                {
                    b.HasOne("CodeFirst.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CodeFirst.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
